---
- name: configure
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Install consul module for python
      pip:
        name: python-consul

    - name: Inject Push Gateway instance to Radon Consul
      consul:
        service_name: "{{ pushgateway_ip }}_push_gateway"
        service_port: "{{ concul_service_port }}"
        service_address: "{{ pushgateway_ip }}"
        host: "{{ concul_ip }}"
