# ---
#   - hosts: localhost
#     vars: 
#        ansible_python_interpreter: /usr/bin/python3

#     # tasks:


#     #   - name: Edit Json File for datapipleine
#     #     script: ModifyJson.py "CopyActivity.json" "input" "{{source_bucket}}/{{file_name}}" "output" "{{destination_bucket}}/{{file_name}}" "pipelineLogUri" "{{log_bucket}}/{{log_directory}}" "period" "{{edit_schedule}}" 
#     #     args:
#     #       executable: python3

#     #   - name: Edit Pipeline definition  
#     #     shell: aws datapipeline put-pipeline-definition --pipeline-id {{pipeline_id}} --pipeline-definition file://CopyActivity.json


---
  - hosts: localhost
    vars: 
       ansible_python_interpreter: /usr/bin/python3

    tasks:

      - name: Edit Pipeline definition  
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{pipeline_id}} --parameter-values myS3InputBucket={{source_bucket}}/{{file_name}} myS3OutputBucket={{destination_bucket}}/{{file_name}} myLogBucket={{log_bucket}}/{{log_directory}} mySchedule="{{edit_schedule}}" --pipeline-definition file://CopyActivity.json



#       - name: Edit Json File for datapipleine
#         script: /Users/chinmaya/Desktop/temp/opera_temp_CCCourse/opera/opera-0.6.1/AWS_pipelines/checkAWS_copy_v1/nodetypes/radon.nodes.datapipeline.Standalone/copy_s3_s3/files/ModifyJson.py "CopyActivity.json" "input" "{{source_bucket}}/{{file_name}}" "output" "{{destination_bucket}}/{{file_name}}" "pipelineLogUri" "{{log_bucket}}/{{log_directory}}" "period" "{{edit_schedule}}" 
#         args:
#           executable: python3
